existential check
1st try checking

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -25,6 +25,16 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
 
+      #check if a file exists in the repo
+      - name: exist or no
+        run: |
+          if test -f "main.py"; then
+            echo "it is there. yay"
+          else
+            echo "main.py not found. sobs"
+            exit 1
+          fi
+          
       # Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world!
